openapi: 3.0.0
info:
  title: Busha API
  contact:
    email: developers@busha.co
  description: |
    ## Introduction
    The **Busha API** is designed to provide businesses with tools for borderless financial transactions and operations, enabling modern, global money management. It serves as the backbone for facilitating:
    - Creation and management of multi-currency balances
    - Retrieval of real-time cryptocurrency rates
    - Substantial data insights for business owners

    Whether you’re a product-driven fintech or a developer building integrations, this API significantly accelerates implementation while reducing financial complexities.
    For detailed guides on API integration, visit our [official documentation]().


    ## Authentication
    All API requests require a **Bearer Token** for authentication, passed in the `Authorization` header.
    Your authorization value is a base64 encoded value of your api key and your secret key.
    You can obtain API tokens via your Busha user or business account. Authentication is mandatory to ensure secure and authorized interactions with the API.
    The API keys from the dashboard provides a base64 encoding of the your authorrization tokens.

    Your generated Key should look like this:
    `VURtNXhWcHueantkpaiewjo0S044MWsadfojienuoxRTiWDJaeWJaTGxxanZ3Ym10OU1RZnVWajVW=`

    Example Header:
    ``` curl
    Authorization: Bearer VURtNXhWcHueantkpaiewjo0S044MWsadfojienuoxRTiWDJaeWJaTGxxanZ3Ym10OU1RZnVWajVW=
    ```

    ## Error Handling
    #Standardized error responses ensure predictable interactions. Errors are detailed for easy debugging and understanding:
    | **Error Code** | **HTTP Status Code** | **Description** |
    | --- | --- | --- |
    | `bad_request` | 400 | Invalid input or malformed request |
    | `unauthorized` | 401 | Invalid or missing authentication |
    | `not_found` | 404 | Resource not found |
    | `service_unavailable` | 503 | Server error |

    Basic Error Example:
    ``` json
    {
      "error": {
        "name": "bad_request",
        "message": "Invalid input data"
      }
    }
    ```

    Schema Error Body Example:
    ``` json
    {
      "error": {
        "name": "bad_request",
        "message": "Invalid input data"
      },
      "schema": {
        "reason": "The request body is defined as an object. However, it does not meet the schema requirements of the specification",
        "fix": "Ensure that the object being submitted, matches the schema correctly"
      }
    }
    ```

    Field Error Body Example:
    ``` json
    {
      "error": {
        "name": "bad_request",
        "message": "Invalid input data"
      },
      "fields": {
        "field1": [
          {
            "reason": "The request body is defined as an object. However, it does not meet the schema requirements of the specification"
          }
        ],
        "field2": [
          {
            "reason": "The request body is defined as an object. However, it does not meet the schema requirements of the specification"
          }
        ]
      }
    }
    ```

    ## Pagination
    Pagination uses cursors provided as:
    The API supports **cursor-based pagination** for endpoints with large datasets. Pagination uses a `next_cursor` and `previous_cursor` returned in the response.
    Example Response Format:
    ``` json
    {
      "current_entries_size": 10,
      "next_cursor": "base64_cursor_value",
      "previous_cursor": "base64_previous_cursor_value"
    }
    ```

    ## Rate Limiting
    Rate limits determine how many API calls can be made in a rolling minute. This ensures fair and optimized use of system resources.

    The rate limits allowed by each resource will be provided with the header:
    ```curl
    x-rate-limit 100
    ```
    If this header does not exist, then the rate limit is set at a default 100 req/min

    Requests exceeding the allocated quota will receive a `429 Too Many Requests` response.

    ##  Common Parameters
    Common parameters enhance consistency across endpoints:
      | **Parameter Name** | **Location** | **Description** | **Example** |
      | --- | --- | --- | --- |
      | `X-BU-PROFILE-ID` | Header | User profile identifier | `BUS_qwejinoiuiqw93ejjw` |
      | `id` | Path | Unique NanoID identifier | `dpt_jweqafajsndiun34fd` |
      | `cursor` | Query | Pagination cursor | `base64_cursor_string` |

    #### Paginated Response Example
      ``` json
      {
        "status": "success",
        "message": "Data retrieved",
        "pagination": {
          "next_cursor": "value_for_next_page",
          "current_entries_size": 20
        },
        "data": [...]
      }
      ```
  version: 1.0.0
servers:
  - url: https://api.sandbox.busha.so
    description: Sandbox Environment
  - url: https://api.busha.co
    description: Production Environment
tags:
  - name: Balances
    description: Handles account balances across different currencies
    x-displayName: Balances
  - name: Currencies
    description: |
      Endpoints to manage supported currencies, their properties, and network details.
    x-displayName: Currencies
  - name: Miscellaneous
    description: Provides auxiliary APIs to complement and enhance other services.
    x-displayName: Miscellaneous
  - name: Pairs
    description: Access trading pair information and rates
    x-displayName: Pairs
  - name: Quotes
    description: Handle quotes requests and responses
    x-displayName: Quotes
  - name: Recipients
    x-displayName: Recipients
  - name: Transactions
    x-displayName: Transactions
  - name: Transfers
    x-displayName: Transfers
paths:
  /v1/balances:
    post:
      security:
        - Auth:
            - balances:write
            - api:write
      tags:
        - Balances
      operationId: createBalance
      summary: Create currency balance
      description: Creates a new balance for managing funds in a specific currency.
    get:
      tags:
        - Balances
      operationId: listBalances
      summary: List all balances
      description: Retrieves all account balances with their current status.
      security:
        - Auth:
            - balances:read
            - api:read
  /v1/balances/{id}:
    get:
      tags:
        - Balances
      operationId: getBalance
      summary: Get balance details
      security:
        - Auth:
            - balances:read
            - api:read
  /v1/currencies:
    get:
      tags:
        - Currencies
      summary: Retrieve supported currencies
      description: |
        Retrieves a list of all supported currencies along with their basic details. This endpoint can be used to display available currencies in wallets or APIs requiring currency data.
      operationId: listCurrencies
      security: []
  /v1/currencies/{code}:
    get:
      tags:
        - Currencies
      summary: Retrieve details of a specific currency
      description: |
        Fetches detailed information about a specific currency using its unique code. This includes details such as network support, decimal precision, and transaction limits.
      operationId: getCurrency
      security: []
  /v1/validate:
    post:
      tags:
        - Miscellaneous
      summary: Validate payment destination
      description: validates a payment destination is valid
      operationId: validatePaymentDestination
      security: []
  /v1/banks:
    get:
      tags:
        - Miscellaneous
      summary: List banks resource
      description: Returns a list of all banks and their bank codes
      operationId: listBanks
      security: []
  /v1/countries:
    get:
      tags:
        - Miscellaneous
      summary: Returns a list of countries
      description: Returns a list of countries and their supported payment channels
      operationId: listCountries
      security: []
  /v1/pairs:
    get:
      tags:
        - Pairs
      summary: List trading pairs
      description: Retrieves all available trading pairs with their current rates.
      operationId: listPairs
      security: []
  /v1/quotes:
    post:
      security:
        - Auth:
            - quotes:write
            - api:write
      summary: Create a new Quote
      description: Create Quote
      operationId: createQuote
      tags:
        - Quotes
    get:
      summary: List Quotes
      description: List Quotes
      operationId: listQuotes
      tags:
        - Quotes
      security:
        - Auth:
            - quotes:read
            - api:read
  /v1/quotes/{id}:
    get:
      summary: Get Quote
      description: Returns a single quote by it's unique ID
      operationId: getQuote
      tags:
        - Quotes
      security:
        - Auth:
            - quotes:read
            - api:read
  /v1/quotes/unauthenticated:
    post:
      security: []
      summary: Create Unauthenticated Quotes
      description: Create Unauthenticated Quote
      operationId: unauthenticatedCreateQuote
      tags:
        - Quotes
  /v1/recipients:
    post:
      security:
        - Auth:
            - recipients:write
            - api:write
      tags:
        - Recipients
      operationId: createRecipient
      summary: Creates a recipient
      description: Create a new recipient for transfers
    get:
      tags:
        - Recipients
      operationId: listRecipients
      summary: List recipients
      description: Retrieve a list of all recipients
      security:
        - Auth:
            - recipients:read
            - api:read
  /v1/recipients/{id}:
    get:
      tags:
        - Recipients
      summary: Retrieve a recipient
      description: Get details of a specific recipient
      operationId: getRecipient
      security:
        - Auth:
            - recipients:read
            - api:read
  /v1/recipient-requirements:
    get:
      tags:
        - Recipients
      summary: List recipient requirements
      description: Retrieve recipient requirements for specific currency and country combinations
      operationId: listRecipientRequirements
      security:
        - Auth:
            - recipients:read
            - api:read
  /v1/recipients/resolve-bank-account:
    post:
      security:
        - Auth:
            - recipients:write
            - api:write
      tags:
        - Recipients
      operationId: resolveBankAccount
      summary: Resolves a bank account
      description: Resolves a bank account for bank transfers
  /v1/transactions:
    get:
      tags:
        - Transactions
      description: Returns a list of transactions
      operationId: listTransactions
      summary: List transactions
      security:
        - Auth:
            - transactions:read
            - api:read
  /v1/transactions/{id}:
    get:
      tags:
        - Transactions
      description: Retrieves a transactions
      operationId: getTransaction
      summary: Get transaction
      security:
        - Auth:
            - transactions:read
            - api:read
  /v1/transfers:
    post:
      security:
        - Auth:
            - transfers:write
            - api:write
      summary: Create transfer
      description: Create a transfer object
      operationId: createTransfer
      tags:
        - Transfers
    get:
      summary: List transfers
      description: Gets all transfers
      operationId: listTransfer
      tags:
        - Transfers
      security:
        - Auth:
            - transfers:read
            - api:read
  /v1/transfers/ramp/{id}:
    get:
      summary: Get Ramp Transfer
      description: Retrieves a ramp transfer
      operationId: getRampTransfer
      tags:
        - Transfers
      security:
        - Auth:
            - transfers:read
            - api:read
  /v1/transfers/{id}:
    get:
      summary: Get transfer
      description: Retrieves a transfer
      operationId: getTransfer
      tags:
        - Transfers
      security:
        - Auth:
            - transfers:read
            - api:read
components:
  securitySchemes:
    Auth:
      type: http
      scheme: bearer
      description: Bearer Authentication