openapi: 3.0.0
info:
  title: Busha API
  contact:
    email: developers@busha.co
  description: |
    ## 1. Introduction
    The **Busha API** is designed to provide businesses with tools for borderless financial transactions and operations, enabling modern, global money management. It serves as the backbone for facilitating:
    - Creation and management of multi-currency balances
    - Retrieval of real-time cryptocurrency rates
    - Substantial data insights for business owners

    Whether you’re a product-driven fintech or a developer building integrations, this API significantly accelerates implementation while reducing financial complexities.
    For detailed guides on API integration, visit our [official documentation]().


    ## 2. Authentication
    All API requests require a **Bearer Token** for authentication, passed in the `Authorization` header.
    Your authorization value is a base64 encoded value of your api key and your secret key.
    You can obtain API tokens via your Busha user or business account. Authentication is mandatory to ensure secure and authorized interactions with the API.
    The API keys from the dashboard provides `apiKey` and `secretKey`
    Generate a base64 encoding of the two keys in this format:
    `<apiKey>:<secretKey>`

    Your generated Key should look like this:
    `VURtNXhWcHueantkpaiewjo0S044MWsadfojienuoxRTiWDJaeWJaTGxxanZ3Ym10OU1RZnVWajVW=`

    Example Header:
    ``` curl
    Authorization: Bearer VURtNXhWcHueantkpaiewjo0S044MWsadfojienuoxRTiWDJaeWJaTGxxanZ3Ym10OU1RZnVWajVW=
    ```

    ## 3. Error Handling
    #Standardized error responses ensure predictable interactions. Errors are detailed for easy debugging and understanding:
    | **Error Code** | **HTTP Status Code** | **Description** |
    | --- | --- | --- |
    | `bad_request` | 400 | Invalid input or malformed request |
    | `unauthorized` | 401 | Invalid or missing authentication |
    | `not_found` | 404 | Resource not found |
    | `service_unavailable` | 503 | Server error |

    Basic Error Example:
    ``` json
    {
      "error": {
        "name": "bad_request",
        "message": "Invalid input data"
      }
    }
    ```

    Schema Error Body Example:
    ``` json
    {
      "error": {
        "name": "bad_request",
        "message": "Invalid input data"
      },
      "schema": {
        "reason": "The request body is defined as an object. However, it does not meet the schema requirements of the specification",
        "fix": "Ensure that the object being submitted, matches the schema correctly"
      }
    }
    ```

    Field Error Body Example:
    ``` json
    {
      "error": {
        "name": "bad_request",
        "message": "Invalid input data"
      },
      "fields": {
        "field1": [
          {
            "reason": "The request body is defined as an object. However, it does not meet the schema requirements of the specification"
          }
        ],
        "field2": [
          {
            "reason": "The request body is defined as an object. However, it does not meet the schema requirements of the specification"
          }
        ]
      }
    }
    ```

    ## 4. Pagination
    Pagination uses cursors provided as:
    The API supports **cursor-based pagination** for endpoints with large datasets. Pagination uses a `next_cursor` and `previous_cursor` returned in the response.
    Example Response Format:
    ``` json
    {
      "current_entries_size": 10,
      "next_cursor": "base64_cursor_value",
      "previous_cursor": "base64_previous_cursor_value"
    }
    ```

    ## 5. Rate Limiting
    Rate limits determine how many API calls can be made in a rolling minute. This ensures fair and optimized use of system resources.

    The rate limits allowed by each resource will be provided with the header:
    ```curl
    x-rate-limit 100
    ```
    If this header does not exist, then the rate limit is set at a default 100 req/min

    Requests exceeding the allocated quota will receive a `429 Too Many Requests` response.

    ##  Common Parameters
    Common parameters enhance consistency across endpoints:
      | **Parameter Name** | **Location** | **Description** | **Example** |
      | --- | --- | --- | --- |
      | `X-BU-PROFILE-ID` | Header | User profile identifier | `BUS_qwejinoiuiqw93ejjw` |
      | `id` | Path | Unique NanoID identifier | `dpt_jweqafajsndiun34fd` |
      | `cursor` | Query | Pagination cursor | `base64_cursor_string` |

    #### Paginated Response Example
      ``` json
      {
        "status": "success",
        "message": "Data retrieved",
        "pagination": {
          "next_cursor": "value_for_next_page",
          "current_entries_size": 20
        },
        "data": [...]
      }
      ```
  version: 1.0.0
servers:
  - url: https://api.sandbox.busha.so
    description: Sandbox Environment
  - url: https://api.busha.so
    description: Production Environment
tags:
  - name: Balances
    description: Handles account balances across different currencies
    x-displayName: Balances
  - name: Currencies
    description: |
      Endpoints to manage supported currencies, their properties, and network details.
    x-displayName: Currencies
  - name: Earn
    description: Main tag for the Earn service
    x-displayName: Earn
  - name: Pairs
    description: Access trading pair information and rates
    x-displayName: Pairs
  - name: Quotes
    description: Handle quotes requests and responses
    x-displayName: Quotes
  - name: Quote
    x-displayName: Quote
  - name: Recipients
    x-displayName: Recipients
  - name: Transfers
    x-displayName: Transfers
paths:
  /v1/balances:
    post:
      security:
        - Auth:
            - balances:write
      tags:
        - Balances
      operationId: createBalance
      summary: Create currency balance
      description: Creates a new balance for managing funds in a specific currency.
    get:
      tags:
        - Balances
      operationId: listBalances
      summary: List all balances
      description: Retrieves all account balances with their current status.
      security:
        - Auth:
            - balances:read
  /v1/balances/{id}:
    get:
      tags:
        - Balances
      operationId: getBalance
      summary: Get balance details
      security:
        - Auth:
            - balances:read
  /v1/currencies:
    get:
      tags:
        - Currencies
      summary: Retrieve supported currencies
      description: |
        Retrieves a list of all supported currencies along with their basic details. This endpoint can be used to display available currencies in wallets or APIs requiring currency data.
      operationId: listCurrencies
      security:
        - Auth:
            - currencies:read
            - currencies:write
  /v1/currencies/{code}:
    get:
      tags:
        - Currencies
      summary: Retrieve details of a specific currency
      description: |
        Fetches detailed information about a specific currency using its unique code. This includes details such as network support, decimal precision, and transaction limits.
      operationId: getCurrency
      security:
        - Auth:
            - currencies:read
            - currencies:write
  /v1/earn/products:
    get:
      tags:
        - Earn
      summary: List All Products For Earn
      description: Retrieves the list of all available products
      operationId: listEarnProducts
      security:
        - Auth:
            - earn:read
  /v1/earn/products/{id}:
    get:
      tags:
        - Earn
      summary: Get Product For Earn
      description: Retrieves the product details for a given product id
      operationId: getEarnProduct
      security:
        - Auth:
            - earn:read
  /v1/earn/subscriptions:
    get:
      tags:
        - Earn
      operationId: listEarnSubscriptions
      summary: List Earn Subscriptions
      description: List All Earn Subscriptions for User
      security:
        - Auth:
            - earn:read
    post:
      security:
        - Auth:
            - earn:write
      tags:
        - Earn
      operationId: createEarnSubscription
      summary: Create Earn Subscription
      description: Creates a new earn subscription.
  /v1/earn/subscriptions/{id}:
    get:
      tags:
        - Earn
      summary: Get Earn Subscription
      description: Retrieves the subscription details for a given subscription id
      operationId: getEarnSubscription
      security:
        - Auth:
            - earn:read
  /v1/earn/redemptions:
    get:
      tags:
        - Earn
      summary: List Earn Redemptions
      description: List all earn redemptions for a user
      operationId: listEarnRedemptions
      security:
        - Auth:
            - earn:read
    post:
      security:
        - Auth:
            - earn:write
      tags:
        - Earn
      summary: Create Earn Redemption
      description: Creates a new earn redemption.
      operationId: createEarnRedemption
  /v1/earn/redemptions/{id}:
    get:
      tags:
        - Earn
      summary: Get Earn Redemption
      description: Retrieves the redemption details for a given redemption id
      operationId: getEarnRedemption
      security:
        - Auth:
            - earn:read
  /v1/earn/earnings:
    get:
      tags:
        - Earn
      summary: List Earn Earnings
      description: List all earn earnings from a yield subscription
      operationId: listEarnEarnings
      security:
        - Auth:
            - earn:read
  /v1/earn/earnings/{id}:
    get:
      tags:
        - Earn
      summary: Retrieve Earn Earnings
      description: Earnings are the interest received from a subscription daily based on the APY of the product.
      operationId: getEarnEarnings
      security:
        - Auth:
            - earn:read
  /v1/earn/positions:
    get:
      tags:
        - Earn
      summary: List Earn Positions
      description: This describes the summary of a user's subscription positions.
      operationId: listEarnPositions
      security:
        - Auth:
            - earn:read
  /v1/earn/positions/{id}:
    get:
      tags:
        - Earn
      summary: Retrieve Earn Positions
      description: This describes the summary of a user's subscription positions.
      operationId: getEarnPositions
      security:
        - Auth:
            - earn:read
  /v1/pairs:
    get:
      tags:
        - Pairs
      summary: List trading pairs
      description: Retrieves all available trading pairs with their current rates.
      operationId: listPairs
      security: []
  /v1/quotes:
    post:
      security:
        - Auth:
            - quotes:write
      summary: Create a new Quote
      description: Create Quote
      operationId: createQuote
      tags:
        - Quote
    get:
      summary: List Quotes
      description: List Quotes
      operationId: listQuotes
      tags:
        - Quote
      security:
        - Auth:
            - quotes:read
  /v1/quotes/{id}:
    get:
      summary: Get Quote
      description: Returns a single quote by it's unique ID
      operationId: getQuote
      tags:
        - Quote
      security:
        - Auth:
            - quotes:read
  /v1/recipients:
    post:
      security:
        - Auth:
            - recipients:write
      tags:
        - Recipients
      operationId: createRecipient
      summary: '[ WIP ] Creates a recipient'
      description: Create a new recipient for transfers
    get:
      tags:
        - Recipients
      operationId: listRecipients
      summary: List recipients
      description: Retrieve a list of all recipients
      security:
        - Auth:
            - recipients:read
  /v1/recipients/{platform_id}:
    get:
      tags:
        - Recipients
      summary: Retrieve a recipient
      description: Get details of a specific recipient
      operationId: getRecipient
      security:
        - Auth:
            - recipients:read
  /v1/recipient-requirements:
    get:
      tags:
        - Recipients
      summary: List recipient requirements
      description: Retrieve recipient requirements for specific currency and country combinations
      operationId: listRecipientRequirements
      security:
        - Auth:
            - recipients:read
  /v1/transfers:
    post:
      security:
        - Auth:
            - transfers:write
      summary: Create transfer
      description: Create a transfer object
      operationId: createTransfer
      tags:
        - Transfers
    get:
      summary: List transfers
      description: Returns a simple greeting from the transfer service
      operationId: listTransfer
      tags:
        - Transfers
      security:
        - Auth:
            - transfers:read
  /v1/transfers/{id}:
    get:
      summary: Get transfer
      description: Retrieves a transfer
      operationId: getTransfer
      tags:
        - Transfers
      security:
        - Auth:
            - transfers:read
components:
  securitySchemes:
    Auth:
      type: http
      scheme: bearer
      description: Bearer Authentication